-- CREATE TABLE categories (
--     id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
--     title VARCHAR(255) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

ALTER TABLE users ADD COLUMN avatar varchar(255) DEFAULT NULL AFTER location;
ALTER TABLE users ADD COLUMN google_id VARCHAR(255) NULL AFTER avatar, ADD COLUMN google_token VARCHAR(255) NULL AFTER google_id;
ALTER TABLE users MODIFY COLUMN phone_number VARCHAR(255) DEFAULT NULL, ADD UNIQUE (phone_number);
ALTER TABLE users MODIFY COLUMN password VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN facebook_id VARCHAR(255) DEFAULT NULL AFTER google_token, ADD COLUMN facebook_token VARCHAR(255) DEFAULT NULL AFTER facebook_id;
